# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go run ./cmd/web"
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules"]

[log]
time = true
