services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - air_tmp:/app/tmp
    environment:
      - POSTGRES_DSN=postgres://agent:agentpass@postgres:5432/agentdb?sslmode=disable
      - REDIS_HOST=redis:6379
      - POSTGRES_HOST=postgres
      - OLLAMA_HOST=http://host.docker.internal:11434
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agentpass
      POSTGRES_DB: agentdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
  air_tmp:
